CRUD処理を備えたRESTAPIを作成
soishiki/Lesson9 pull request #1
Opened 2022-10-24 08:44 UTC by soishiki

## 第10回課題
CRUD処理を備えたRESTAPIを作成

### 使用するデータベース（初期状態）
| ID |  NAME   | AGE |
|:---|:-------:|----:|
| 1  |  Taro   |  30 |
| 2  |  Jiro   |  25 |
| 3  | Saburo  |  22 |
| 4  | Kazuko  |  25 |
| 5  | Michiko |  22 |
 | 6  |  Yoko   |  20 |`

### APIの動作
```bash
### GETメソッド
# すべてのユーザー名を取得
curl -X GET 'http://localhost:8080/users'

# 指定した年齢のユーザー名を取得
curl -X GET 'http://localhost:8080/users?age=XX'

# 指定したIDのユーザーデータ(ID, NAME, AGE)を取得
curl -X GET 'http://localhost:8080/users/XX'

### POSTメソッド
# 新しいユーザーを登録
curl -X POST 'http://localhost:8080/users' -H 'Content-Type: application/json' -d '{"name": "XX", "age": XX}' -i

### PATCHメソッド
# 指定したIDのユーザーデータを更新
curl -X PATCH 'http://localhost:8080/users/XX' -H 'Content-Type: application/json' -d '{"name": "XX", "age": XX}' -i

### DELETEメソッド
# 指定したIDのユーザーデータを更新
curl -X DELETE 'http://localhost:8080/users/XX'
```

## 実行結果
- すべてのユーザー名を取得
![image](https://user-images.githubusercontent.com/85924503/197486131-f0035e23-c25d-45a3-846b-94fdbdf92b3c.png)

- 指定した年齢のユーザー名を取得
![image](https://user-images.githubusercontent.com/85924503/197486429-08d85fde-924a-4236-a533-40463389e173.png)

- 指定したIDのユーザーデータ(ID, NAME, AGEを取得)
![image](https://user-images.githubusercontent.com/85924503/197486585-99782d03-0f66-4530-ab97-8ae339a16dab.png)

- 新しいユーザーを登録
![image](https://user-images.githubusercontent.com/85924503/197486958-b10e13bf-20a6-4b94-8d9c-ad53da39128a.png)

- 指定したIDのユーザーデータを更新
![image](https://user-images.githubusercontent.com/85924503/197486700-dae30110-9227-4db2-ab1d-eff65c3f2f73.png)

- 指定したIDのユーザーデータを更新
![image](https://user-images.githubusercontent.com/85924503/197488454-5440fe2d-fd0f-43b6-b050-7d81aad8a527.png)

2022-10-24 09:27 UTC, YudaiNoda3576 requested changes
コメントしています！

2022-10-24 09:27 UTC, YudaiNoda3576 commented on src/main/java/net/raisetechPractice/UserManagementApp/controller/UserController.java
> +        return ResponseEntity.ok(Map.of("names", names));
ResponseEntityを使用しないパターンでも試しに実装してみてください！

2022-10-24 09:27 UTC, YudaiNoda3576 commented on src/main/java/net/raisetechPractice/UserManagementApp/controller/UserController.java
> +    public ResponseEntity<Map<String, String>> NotFound(NotFoundException notFoundException, HttpServletRequest request){
ExceptionHandlerはアプリケーション全体で使用することになると思うのでExceptionディレクトリなどを作成してそこに別クラスに定義した方が良いと思います１

2022-10-24 09:27 UTC, YudaiNoda3576 commented on src/main/java/net/raisetechPractice/UserManagementApp/controller/UserResponse.java
> +}
改行が保存時に含まれるようにIDEの設定を変えておきましょうか！

2022-10-24 09:27 UTC, YudaiNoda3576 commented on src/main/java/net/raisetechPractice/UserManagementApp/entity/User.java
> +@Getter
class全体に付与しているパターンとそうでないパターンはどういった理由で使い分けられていますか？
もしなければ統一しましょう！

2022-10-24 09:27 UTC, YudaiNoda3576 commented on src/main/java/net/raisetechPractice/UserManagementApp/service/UserService.java
> +
ここの空白行を入れるように統一しておきましょう！

2022-10-24 09:27 UTC, YudaiNoda3576 commented on src/main/java/net/raisetechPractice/UserManagementApp/controller/UserController.java
> +        if (age == null) {
ここはJavaでageの有無によってハンドリングするのではなく、MyBatisでハンドリングする方が良いと思います！
そうすると、`findUsersByAge`のような新しいメソッドを定義しなくても良くなると思います！

2022-10-25 04:35 UTC, soishiki reviewed
コメントありがとうございます！
ご指摘事項について修正してみました。
(https://github.com/soishiki/Lesson9/pull/1/commits/ee28ef906d884193ff3bbd14f81d09679825eb09)

お手数をおかけしますが再度ご確認お願いします。

2022-10-25 04:35 UTC, soishiki commented on src/main/java/net/raisetechPractice/UserManagementApp/controller/UserController.java
> +        if (age == null) {
ageの有無を`UserMapper.xml`のSQLに移動して
findUsersByAgeメソッドを削除してみました。

2022-10-25 04:35 UTC, soishiki commented on src/main/java/net/raisetechPractice/UserManagementApp/controller/UserController.java
> +        return ResponseEntity.ok(Map.of("names", names));
@ResponseStatusのアノテーションでステータスコードを設定して
ResponseEntityを削除してみました。

2022-10-25 04:35 UTC, soishiki commented on src/main/java/net/raisetechPractice/UserManagementApp/controller/UserController.java
> +    public ResponseEntity<Map<String, String>> NotFound(NotFoundException notFoundException, HttpServletRequest request){
`exception/NotFoundExceptionController.java`に移動しました。

2022-10-25 04:35 UTC, soishiki commented on src/main/java/net/raisetechPractice/UserManagementApp/controller/UserResponse.java
> +}
IDEの設定を変更しました。
![image](https://user-images.githubusercontent.com/85924503/197683211-487b6a3f-b379-4de9-8696-36d620c7e1d7.png)

2022-10-25 04:35 UTC, soishiki commented on src/main/java/net/raisetechPractice/UserManagementApp/entity/User.java
> +@Getter
付与の仕方がばらばらになってましたね。。
class全体に付与するように修正しました！

2022-10-25 04:35 UTC, soishiki commented on src/main/java/net/raisetechPractice/UserManagementApp/service/UserService.java
> +
メソッドの間に空白行を入れるように統一しました。

2022-10-25 07:32 UTC, YudaiNoda3576 requested changes
コメントしています！

2022-10-25 07:32 UTC, YudaiNoda3576 commented on src/main/java/net/raisetechPractice/UserManagementApp/form/UserForm.java
> +@Setter
このクラスのフィールドは全てsetterが必要でしょうか？
setterはカプセル化に穴を開ける存在（誰でもこのオブジェクトのフィールドを書き換えることができるもの）なので不用意に定義しないのが無難です。

なので、Setterは必要なフィールドにのみ定義すると良いかと思います！

2022-10-25 07:59 UTC, soishiki commented on src/main/java/net/raisetechPractice/UserManagementApp/form/UserForm.java
> +@Setter
ご指摘ありがとうございます！
Setterを必要なフィールドのみに設定しました。https://github.com/soishiki/Lesson9/pull/1/commits/a223dd117e83281b6f4cca1ef53d5b77307a6506

2022-10-25 08:30 UTC, YudaiNoda3576 commented
![LGTM](https://images.lgtmgen.org/28d47ba0-ccfe-462e-bac0-c157b1db3f1e)

2022-10-25 11:45 UTC, merged